---
title: "endgame"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(SDMtune)
library(blockCV)
library(ENMeval)
library(raster)
library(sf)
library(sp)
library(zeallot)
library(rJava)
library(dismo)
library(vegan)
```
```{r}
library(furrr)
future::plan(multisession, workers = 32)
memory.limit(9999999999)
```

```{r}

names.data.reptile <- vector()
for(i in 1:length(data.reptile)){
names.data.reptile[i] <- data.reptile[[i]]@species  
}
names.data.amphibian <- vector()
for(i in 1:length(data.amphibian)){
names.data.amphibian[i] <- data.amphibian[[i]]@species  
}




data.all <- rbind(data.frame(species = names.data.pcnm.reptile,
                             p.long = data.pcnm.reptile))
```



















load PCNM model
```{r}

data.pcnm.reptile






df.model.p <- list()
for(i in 1:length(data.pcnm.reptile)){
df.model.p[[i]] <- cbind(data.pcnm.reptile[[i]]@coords[data.pcnm.reptile[[i]]@pa == 1,],
                         data.pcnm.reptile[[i]]@data[data.pcnm.reptile[[i]]@pa == 1,])
}

df.model.a <- list()
for(i in 1:length(data.pcnm.reptile)){
df.model.a[[i]] <- cbind(data.pcnm.reptile[[i]]@coords[data.pcnm.reptile[[i]]@pa == 0,],
                         data.pcnm.reptile[[i]]@data[data.pcnm.reptile[[i]]@pa == 0,])
}

df.model.p <- list()
for(i in 1:length(model_spcv4k.pcnm_reptile)){
df.model.p[[i]] <- cbind(model_spcv4k.pcnm_reptile[[i]]@data@coords[model_spcv4k.pcnm_reptile[[i]]@data@pa == 1,],
                         model_spcv4k.pcnm_reptile[[i]]@data@data[model_spcv4k.pcnm_reptile[[i]]@data@pa == 1,])
}

df.model.a <- list()
for(i in 1:length(model_spcv4k.pcnm_reptile)){
df.model.a[[i]] <- cbind(model_spcv4k.pcnm_reptile[[i]]@data@coords[model_spcv4k.pcnm_reptile[[i]]@data@pa == 0,],
                         model_spcv4k.pcnm_reptile[[i]]@data@data[model_spcv4k.pcnm_reptile[[i]]@data@pa == 0,])
}


df.model.p <- list()
for(i in 1:length(model_rndcv4k.pcnm_amphibian)){
df.model.p[[i]] <- cbind(model_rndcv4k.pcnm_amphibian[[i]]@data@coords[model_rndcv4k.pcnm_amphibian[[i]]@data@pa == 1,],
                         model_rndcv4k.pcnm_amphibian[[i]]@data@data[model_rndcv4k.pcnm_amphibian[[i]]@data@pa == 1,])
}

df.model.a <- list()
for(i in 1:length(model_rndcv4k.pcnm_amphibian)){
df.model.a[[i]] <- cbind(model_rndcv4k.pcnm_amphibian[[i]]@data@coords[model_rndcv4k.pcnm_amphibian[[i]]@data@pa == 0,],
                         model_rndcv4k.pcnm_amphibian[[i]]@data@data[model_rndcv4k.pcnm_amphibian[[i]]@data@pa == 0,])
}

df.model.p <- list()
for(i in 1:length(model_spcv4k.pcnm_amphibian)){
df.model.p[[i]] <- cbind(model_spcv4k.pcnm_amphibian[[i]]@data@coords[model_spcv4k.pcnm_amphibian[[i]]@data@pa == 1,],
                         model_spcv4k.pcnm_amphibian[[i]]@data@data[model_spcv4k.pcnm_amphibian[[i]]@data@pa == 1,])
}

df.model.a <- list()
for(i in 1:length(model_spcv4k.pcnm_amphibian)){
df.model.a[[i]] <- cbind(model_spcv4k.pcnm_amphibian[[i]]@data@coords[model_spcv4k.pcnm_amphibian[[i]]@data@pa == 0,],
                         model_spcv4k.pcnm_amphibian[[i]]@data@data[model_spcv4k.pcnm_amphibian[[i]]@data@pa == 0,])
}












sf.model.p  <- list()
for(i in 1:length(df.model.p)){
sf.model.p[[i]] <- st_as_sf(df.model.p[[i]],
                            coords = c("X", "Y"), 
                            crs = 4326,
                            remove = F)
}

sf.model.a  <- list()
for(i in 1:length(df.model.a)){
sf.model.a[[i]] <-  st_as_sf(df.model.a[[i]],
                            coords = c("X", "Y"), 
                            crs = 4326,
                            remove = F)
}



for(i in 1:length(sf.model.p)){
st_join(sf.model.p[[i]], 
        sf.model.a[[i]], 
 join = st_nearest_feature) -> sf.model.p[[i]]}



for(i in 1:length(sf.model.p)){
  sf.model.p[[i]] <- sf.model.p[[i]][,-(8:28)] #get pcnm variables only from background 
}

for(i in 1:length(sf.model.p)){
names(sf.model.p[[i]])[-22] <- str_sub(names(sf.model.p[[i]]), 1,-3)[-22]} #fix names

for( i in 1:length(sf.model.p)){#erase geometry
  st_geometry(sf.model.p[[i]]) <- NULL
}



for(i in 1:length(sf.model.p)){
  data.pcnm.reptile[[i]]@coords <- sf.model.p[[i]][,c("X","Y")]
  data.pcnm.reptile[[i]]@data[data.pcnm.reptile[[i]]@pa==1,] <- sf.model.p[[i]][,3:21]
}





t.t.pcnm.reptile_0.2 <- list()
for (i in 1:length(data.pcnm.reptile)){t.t.pcnm.reptile_0.2[[i]] <- trainValTest(data.pcnm.reptile[[i]], test = 0.2, only_presence = FALSE, seed = 1)}

rnd4k <- function(x){randomFolds(x[[1]], 
                                 k = 4,
                                 only_presence = FALSE,
                                 seed = 1)}

folds.rnd4k_reptile <- map(t.t.pcnm.reptile_0.2, rnd4k)

```

```{r}

my.maxent <- function(x,y){
  SDMtune::train(method = "Maxent",
                 data = x[[1]],
                 folds = y)
}

my.maxnet <- function(x,y){
  SDMtune::train(method = "Maxnet",
                 data = x[[1]],
                 folds = y)
}


maxent_rndcv4k.pcnm_reptile <- future_map2(t.t.pcnm.reptile_0.2, folds.rnd4k_reptile,
                                    my.maxent, 
                                    .options = furrr_options(seed = TRUE),
                                    .progress = T)


maxnet_rndcv4k.pcnm_reptile <- future_map2(t.t.pcnm.reptile_0.2, folds.rnd4k_reptile,
                                    my.maxnet, 
                                    .options = furrr_options(seed = TRUE),
                                    .progress = T)

```


```{r}





for(i in 1:length(sf.model.p)){
  model_rndcv4k.pcnm_reptile[[i]]@data@coords <- sf.model.p[[i]][,c("X","Y")]
  model_rndcv4k.pcnm_reptile[[i]]@data@data[model_rndcv4k.pcnm_reptile[[i]]@data@pa==1,] <- sf.model.p[[i]][,3:21]
}

for(i in 1:length(sf.model.p)){
  model_spcv4k.pcnm_reptile[[i]]@data@coords <- sf.model.p[[i]][,c("X","Y")]
  model_spcv4k.pcnm_reptile[[i]]@data@data[model_spcv4k.pcnm_reptile[[i]]@data@pa==1,] <- sf.model.p[[i]][,3:21]
  }

for(i in 1:length(sf.model.p)){
  model_rndcv4k.pcnm_amphibian[[i]]@data@coords <- sf.model.p[[i]][,c("X","Y")]
  model_rndcv4k.pcnm_amphibian[[i]]@data@data[model_rndcv4k.pcnm_amphibian[[i]]@data@pa==1,] <- sf.model.p[[i]][,3:21]
}

for(i in 1:length(sf.model.p)){
  model_spcv4k.pcnm_amphibian[[i]]@data@coords <- sf.model.p[[i]][,c("X","Y")]
  model_spcv4k.pcnm_amphibian[[i]]@data@data[model_spcv4k.pcnm_amphibian[[i]]@data@pa==1,] <- sf.model.p[[i]][,3:21]
  }




model_rndcv4k.pcnm_reptile <- future_map(model_rndcv4k.pcnm_reptile,
                                    my.maxent, 
                                    .options = furrr_options(seed = TRUE),
                                    .progress = T)

model_spcv4k.pcnm_reptile <- future_map(model_spcv4k.pcnm_reptile,
                                    my.maxent, 
                                    .options = furrr_options(seed = TRUE),
                                    .progress = T)

model_rndcv4k.pcnm_amphibian <- future_map(model_rndcv4k.pcnm_amphibian,
                                    my.maxent, 
                                    .options = furrr_options(seed = TRUE),
                                    .progress = T)

model_spcv4k.pcnm_amphibian <- future_map(model_spcv4k.pcnm_amphibian,
                                    my.maxent, 
                                    .options = furrr_options(seed = TRUE),
                                    .progress = T)

model_spcv4k.pcnm_amphibian <- future_map(model_spcv4k.pcnm_amphibian, #omitted rror...
                                    my.maxnet, 
                                    .options = furrr_options(seed = TRUE),
                                    .progress = T)

```



```{r}
test_rndcv4k.pcnm.maxent_reptile <- list()
for(i in 1:length(maxent_rndcv4k.pcnm_reptile)){
test_rndcv4k.pcnm.maxent_reptile[[i]] <- list(SDMtune::predict(maxent_rndcv4k.pcnm_reptile[[i]], 
                                                  t.t.pcnm.reptile_0.2[[i]][[2]],
                                                  fun = "mean",
                                                  type = "cloglog"),
                                 SDMtune::predict(maxent_rndcv4k.pcnm_reptile[[i]],
                                 t.t.pcnm.reptile_0.2[[i]][[2]]@data[t.t.pcnm.reptile_0.2[[i]][[2]]@pa == 1,],
                                                   fun = "mean",
                                                   type = "cloglog"))}



test_rndcv4k.pcnm.maxnet_reptile <- list()
for(i in 1:length(maxnet_rndcv4k.pcnm_reptile)){
test_rndcv4k.pcnm.maxnet_reptile[[i]] <- list(SDMtune::predict(maxnet_rndcv4k.pcnm_reptile[[i]], 
                                                  t.t.pcnm.reptile_0.2[[i]][[2]],
                                                  fun = "mean",
                                                  type = "cloglog"),
                                 SDMtune::predict(maxnet_rndcv4k.pcnm_reptile[[i]],
                                 t.t.pcnm.reptile_0.2[[i]][[2]]@data[t.t.pcnm.reptile_0.2[[i]][[2]]@pa == 1,],
                                                   fun = "mean",
                                                   type = "cloglog"))}
```




```{r}
hist(test_rndcv4k.pcnm.maxent_reptile[[1]][[2]], 25)
hist(test_rndcv4k.pcnm.maxnet_reptile[[1]][[2]], 10)
```
```{r}
which(test_rndcv4k.pcnm.maxent_reptile[[1]][[2]] == test_rndcv4k.pcnm.maxnet_reptile[[1]][[2]])
```
```{r}
sd(test_rndcv4k.pcnm.maxent_reptile[[1]][[2]] - test_rndcv4k.pcnm.maxnet_reptile[[1]][[2]])
```



```{r}
AUC_rnd.train.pcnm.reptile <- vector()
for(i in 1:length(maxent_rndcv4k.pcnm_reptile)){
AUC_rnd.train.pcnm.reptile[i] <- SDMtune::auc(model = maxent_rndcv4k.pcnm_reptile[[i]])
}

AUC_rnd.train.bio.reptile<- vector()
for(i in 1:length(model_rndcv4k_reptile)){
AUC_rnd.train.bio.reptile[i] <- SDMtune::auc(model = model_rndcv4k_reptile[[i]])
}

AUC_rnd.train.pcnm.reptile <- vector()
for(i in 1:length(maxnet_rndcv4k.pcnm_reptile)){
AUC_rnd.train.pcnm.reptile[i] <- SDMtune::auc(model = maxnet_rndcv4k.pcnm_reptile[[i]])
}

which(AUC_rnd.train.bio.reptile < AUC_rnd.train.pcnm.reptile)
```



```{r}

auc  <- vector()
for(i in 1:length(newmodel)){
auc[i] <- SDMtune::auc(newmodel[[i]])
}

auc2  <- vector()
for(i in 1:length(newmodel)){
auc2[i] <- SDMtune::auc(newmodel[[i]], t.t.pcnm.reptile_0.2[[i]][[2]])
}

auc3  <- vector()
for(i in 1:length(newmodel2)){
auc3[i] <- SDMtune::auc(newmodel2[[i]])
}

auc2  <- vector()
for(i in 1:length(newmodel)){
auc2[i] <- SDMtune::auc(newmodel[[i]], t.t.pcnm.reptile_0.2[[i]][[2]])
}


df <- data.frame(auc = auc,
                 auc2 = auc2)

ggplot(data = df) +
      geom_point(aes(x = auc, y = auc2), size = 1) +
      geom_abline(intercept = 0, slope = 1, size = 0.5) +
      labs(title = "Boyce P/E plot(Amphibian)",
           y = "출현/기대 비율",
           x = "서식처 적합도",
           size = 15) +
      theme_light() +
      theme(strip.text.x = element_text(size = 9, colour = "black"),
        strip.background = element_rect(colour="gray",
                                        fill="white")) -> plot


test_rndcv4k.pcnm_reptile <- list()
for(i in 1:length(model_rndcv4k.pcnm_reptile)){
test_rndcv4k.pcnm_reptile[[i]] <- list(SDMtune::predict(model_rndcv4k.pcnm_reptile[[i]], 
                                                  t.t.pcnm.reptile_0.2[[i]][[2]],
                                                  fun = "mean",
                                                  type = "cloglog"),
                                 SDMtune::predict(model_rndcv4k.pcnm_reptile[[i]],
                                 t.t.pcnm.reptile_0.2[[i]][[2]]@data[t.t.pcnm.reptile_0.2[[i]][[2]]@pa == 1,],
                                                   fun = "mean",
                                                   type = "cloglog")
                                )} #전부다는 [[1]]에, 출현은 [[2]]에


boyce.test.rnd.pcnm_reptile <- list()
for(i in 1:length(test_rndcv4k.pcnm_reptile)){
boyce.test.rnd.pcnm_reptile[[i]] <- my.boyce(test_rndcv4k.pcnm_reptile[[i]][[1]], test_rndcv4k.pcnm_reptile[[i]][[2]])  
}

BOYCE_rnd.test.pcnm.reptile <- vector()
for(i in 1:length(boyce.test.rnd.pcnm_reptile)){
 BOYCE_rnd.test.pcnm.reptile[i] <- boyce.test.rnd.pcnm_reptile[[i]]$Spearman.cor  
}

```

